-define(BUFF_DIZZY, 			1).
-define(BUFF_SLIENT, 			2).
-define(BUFF_DISARM, 			3).
-define(BUFF_POISONING, 		4).
-define(BUFF_BLOODING, 			5).
-define(BUFF_REDUCE_ATT,		6).
-define(BUFF_REDUCE_DEF, 		7).
-define(BUFF_REDUCE_HIT, 		8).
-define(BUFF_ADD_WEEK, 			9).
-define(BUFF_REDUCE_MOVE, 		10).
-define(BUFF_QINGLONG_SHIELD, 	11).	%%青龙盾
-define(BUFF_BAIHU_SHIELD,		12).	%%白虎盾
-define(BUFF_XUANWU_SHIELD, 	13).	%%玄武盾
-define(BUFF_ZHUQUE_SHIELD, 	14).	%%朱雀盾
-define(BUFF_POISON_RESIST, 	15).	%%加毒抗
-define(BUFF_DIZZY_RESIST, 		16).	%%加晕抗
-define(BUFF_DIZZY_REDUCE_CD, 	17).	%%减少晕眩触发CD
-define(BUFF_POISON_ADD_HURT, 	18).	%%增加毒效果层数
-define(BUFF_ADD_DIZZY,			19).    %%增加晕眩概率
-define(BUFF_ADD_POISON,		20).    %%增加毒效果百分比
-define(BUFF_INVISIBLE,			36).    %%隐身
-define(BUFF_UNBEATABLE,		43).    %%无敌
-define(BUFF_NO_NUQI,			6019).  %%释放技能时不增加怒气
