{'src/*/*',    
    [debug_info,   
    {i,"include"},   
    {outdir,"ebin"}   
    ]}.

{'src/*',
    [debug_info,
    {i,"include"},
    {outdir,"ebin"}
    ]}.

{'src/*/*/*',
    [debug_info,
    {i,"include"},
    {outdir,"ebin"}
    ]}.

{'test/*',
    [debug_info,
    {i,"include"},
    {outdir,"ebin"}
    ]}.

{'tools/*',
    [debug_info,
    {i,"include"},
    {outdir,"ebin"}
    ]}.  

